// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwgnygxddaxpfkmlyrqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3Z255Z3hkZGF4cGZrbWx5cnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTQ4OTgsImV4cCI6MjA2ODQ5MDg5OH0.2PuRCYlFYqW1nkRBjnEJrmda8DYvt9UL1Y1cdYzYX1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});